# Generated by Django 3.1.4 on 2021-04-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70)),
                ('Entry_time', models.TimeField()),
                ('Reason_of_visit', models.CharField(max_length=250)),
                ('Whom_to_meet', models.CharField(max_length=250)),
                ('Exit_time', models.TimeField()),
            ],
        ),
    ]
